### PR TITLE
Mention Web of Things WG in Coordination

### LINKED ISSUE #93: Mention Web of Things WG in Coordination
The scope of DAS WG is to develop browser APIs, and WoT people are also getting interested in Web browsers (including embedded browsers and usual Web browsers to provide user interface for IoT services). Since the [updated WoT WG charter](https://www.w3.org/2020/01/wot-wg-charter.html#w3c-coordination) also includes DAS WG within the Coordination section, I suggest that we mention WoT in the Coordination section as well.

### PR DESCRIPTION
**Pull request by xfq**
Fix #93.

### CODE REVIEW

**Review by anssiko — APPROVED** [review]

**Comment by ashimura** [comment]
Thanks a lot for generating the text to be included ind the proposed DAS Charter, @xfq !

I talked with the WoT Chairs and the Editors about this, and we think the current proposed text might be a bit misleading. So we're now generating some possible alternative text.

**Review by ashimura — CHANGES_REQUESTED** [review]
I'm still waiting for the response from the WoT Chairs/Editors but think something like this would be better:
[[
This group defines Web-based abstract architecture and a data model based on JSON-LD for IoT interoperability, and coordination on APIs for sensors, e.g., geolocation information, is expected.
]]

**Comment by mlagally** [comment]
I suggest to keep this more general and refer to sensor data. Coordination should ensure to align terminology and vocabulary:

"The WoT group defines a Web-based abstract architecture and a data model based on JSON-LD for IoT interoperability. Coordination on terminology and vocabulary of sensor data, e.g., geolocation information, is expected."

**Comment by mmccool** [comment]
I would like to support the updated description proposed by Michael Lagally.   In particular I do think we need consistent semantics and terminology for things like geolocation data to avoid developer confusion, even if the WoT and D&S APIs are in distinct contexts (IoT network APIs vs. Browser JS APIs).

**Comment by sebastiankb** [comment]
+1

**Review by ashimura — CHANGES_REQUESTED** [review]
Got confirmation from the WoT Chairs/Editors now, and we'd like to suggest the following text should be included:
[[
The WoT group defines a Web-based abstract architecture and a data model based on JSON-LD for IoT interoperability. Coordination on terminology and vocabulary of sensor data, e.g., geolocation information, is expected.
]]

**Comment by xfq** [comment]
Merging. Thank you all!

**Comment by anssiko** [comment]
The proposed text is asymmetrical with the corresponding text in the WoT WG charter:

> Device and Sensors Working Group
>For coordination on APIs for sensors and actuators

https://www.w3.org/2020/01/wot-wg-charter.html#coordination

APIs vs. terminology. I prefer coordination on non-normative terminology better.

Nit: Devices (plural).

**Comment by mmccool** [comment]
I agree, we should update the text in the WoT charter to be symmetric.

**Pull request merged**
