### PR TITLE
Charter next

### PR DESCRIPTION
**Pull request by anssiko**

### CODE REVIEW

**Comment by xfq** [comment]
I added Netlify to make it easier to review the rendered HTML of pull requests.

**Comment by anssiko** [comment]
@xfq thanks, does Netlify provide diff similar to pr-preview? [Netlify docs](https://docs.netlify.com/site-deploys/deploy-previews/) did not mention.

And while we’re here, can we rename the repo to das-charter without breaking links?

**Comment by xfq** [comment]
> @xfq thanks, does Netlify provide diff similar to pr-preview? [Netlify docs](https://docs.netlify.com/site-deploys/deploy-previews/) did not mention.

No. We can use [PR Preview](https://github.com/tobie/pr-preview) to provide a diff. Although it can also provide previews, it has been unstable recently and only supports previews of a single document in a repo.

**Comment by xfq** [comment]
> And while we’re here, can we rename the repo to das-charter without breaking links?

I'll look into it.

**Comment by anssiko** [comment]
@xfq I notice you've renamed the repo, thanks! It looks like redirects do not work yet, e.g. https://github.com/w3c/dap-charter/pull/122 should take us here, but I get 404. You're probably working on this, so just FYI.

**Comment by xfq** [comment]
GitHub automatically redirect references to the issues/PRs from the old name to the new one, but **not** GitHub Pages, so I created a `dap-charter` repo after renaming the repo to [redirect the **rendered** charter](https://github.com/w3c/dap-charter/blob/main/DASCharter-2021.html). But doing this will make redirects of issues/PRs not work.

I don't have a good solution at the moment, but in order to avoid this kind of problem in the future, one approach I think of is to use Netlify (https://w3c-das-charter.netlify.app/DASCharter-2021.html) (or Vercel etc.) instead of GitHub Pages (https://w3c.github.io/das-charter/DASCharter-2021.html) for the rendered HTML. Since Netlify is not strongly coupled to a GitHub repo, we can configure the redirects ourselves.

**Comment by anssiko** [comment]
@xfq here’s an example of a solution that works without breaking any links: https://github.com/webscreens/webscreens.github.io/blob/master/window-placement/index.html

**Comment by xfq** [comment]
Great idea! Filed https://github.com/w3c/w3c.github.io/pull/108

**Comment by anssiko** [comment]
Superseded by #126

**Pull request closed without merging**
