### PR TITLE
Geolocation api

### PR DESCRIPTION
**Pull request by plehegar**
Add geolocation API for maintenance purpose

### CODE REVIEW

**Comment by plehegar** [comment]
Fixes #76

**Comment by anssiko** [comment]
Thanks @plehegar, looks good to me.

@wseltzer please take a look at this PR and merge if it looks good to you too.

This PR blocks https://github.com/w3c/geolocation-api/issues/19 that is considered specification maintenance (aligning Geolocation API spec with the evolving WebIDL spec).

**Review by wseltzer — APPROVED** [review]
looks fine (link changes probably unnecessary -- hope they don't cause additional noise)

**Comment by anssiko** [comment]
@wseltzer I'm wondering whether we could land the fix to the ED spec before the AC review of the charter amendment concludes https://lists.w3.org/Archives/Public/public-new-work/2019Feb/0002.html and do the WD publication when the AC review concludes?

**Comment by plehegar** [comment]
@anssiko sorry, too many things up in the air. What's the ED fix that needs to be done? We should be able to land it.

**Comment by anssiko** [comment]
@plehegar, remove [NoInterfaceObject] from couple of interfaces, details in https://github.com/w3c/geolocation-api/issues/19

**Comment by plehegar** [comment]
Ah, yes. It's ok to land the fix before the end of the AC review.

**Pull request merged**
